server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://rm-cn-wwo3dw2zk00247zo.rwlb.rds.aliyuncs.com:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gssun
    password: 20030608@syj

mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.tust.pojo.entity

